// user-center-react-frontend/src/pages/admin/user-manage/components/CreateUserModal.tsx
import { ModalForm, ProFormRadio, ProFormText, ProFormTextArea } from '@ant-design/pro-components';
import {
  CameraOutlined,
  IdcardOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LockOutlined,
  MailOutlined,
  ManOutlined,
  PhoneOutlined,
  PlusOutlined,
  SafetyOutlined,
  TeamOutlined,
  UserOutlined,
  WomanOutlined,
} from '@ant-design/icons';
import { Alert, Avatar, Divider, Space, Spin, Tag, Typography, Upload } from 'antd';
import React, { useState } from 'react';
import { useUserOperations } from '../hooks/useUserOperations';

const { Text } = Typography;

interface CreateUserModalProps {
  visible: boolean;
  onVisibleChange: (visible: boolean) => void;
  onFinish: (values: API.AdminAddUserParams) => Promise<boolean>;
}

/**
 * 添加用户弹窗组件
 */
const CreateUserModal: React.FC<CreateUserModalProps> = ({
  visible,
  onVisibleChange,
  onFinish,
}) => {
  const [avatarUrl, setAvatarUrl] = useState<string>('');
  const [passwordStrength, setPasswordStrength] = useState(0);
  const { handleAvatarUpload, uploading } = useUserOperations();

  /**
   * 处理头像上传
   */
  const onAvatarUpload = async (file: File) => {
    const url = await handleAvatarUpload(file);
    if (url) {
      setAvatarUrl(url);
    }
    return false;
  };

  /**
   * 计算密码强度
   */
  const calculatePasswordStrength = (password: string) => {
    if (!password) return 0;
    let strength = 0;
    // 长度
    if (password.length >= 8) strength += 25;
    if (password.length >= 12) strength += 25;
    // 包含小写字母
    if (/[a-z]/.test(password)) strength += 12.5;
    // 包含大写字母
    if (/[A-Z]/.test(password)) strength += 12.5;
    // 包含数字
    if (/\d/.test(password)) strength += 12.5;
    // 包含特殊字符
    if (/[~`!@#$%^&*()\-_=+[{\]}\\|;:'",<.>/?]/.test(password)) strength += 12.5;
    return Math.min(strength, 100);
  };

  /**
   * 密码强度颜色
   */
  const getPasswordStrengthColor = (strength: number) => {
    if (strength < 40) return '#ff4d4f';
    if (strength < 70) return '#faad14';
    return '#52c41a';
  };

  /**
   * 密码强度文本
   */
  const getPasswordStrengthText = (strength: number) => {
    if (strength < 40) return '弱';
    if (strength < 70) return '中';
    return '强';
  };

  return (
    <>
      <style>{`
        @keyframes slideInFromTop {
          from {
            opacity: 0;
            transform: translateY(-20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        @keyframes fadeIn {
          from {
            opacity: 0;
          }
          to {
            opacity: 1;
          }
        }
        @keyframes scaleIn {
          from {
            opacity: 0;
            transform: scale(0.9);
          }
          to {
            opacity: 1;
            transform: scale(1);
          }
        }
        .create-card {
          animation: slideInFromTop 0.5s ease-out;
        }
        .info-section {
          animation: fadeIn 0.6s ease-out;
        }
        .avatar-section {
          animation: scaleIn 0.5s ease-out;
        }
        .avatar-upload-wrapper {
          position: relative;
          display: inline-block;
          cursor: pointer;
        }
        .avatar-upload-wrapper:hover .avatar-mask {
          opacity: 1;
        }
        .avatar-mask {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          background: rgba(0, 0, 0, 0.5);
          border-radius: 50%;
          opacity: 0;
          transition: opacity 0.3s;
          color: #fff;
          font-size: 14px;
        }
        .avatar-mask .camera-icon {
          font-size: 24px;
          margin-bottom: 8px;
        }
        .password-strength-bar {
          height: 4px;
          background: #f0f0f0;
          border-radius: 2px;
          overflow: hidden;
          margin-top: 8px;
        }
        .password-strength-fill {
          height: 100%;
          transition: width 0.3s, background-color 0.3s;
        }
      `}</style>
      <ModalForm<API.AdminAddUserParams>
        title={
          <Space style={{ fontSize: '16px', fontWeight: 600 }}>
            <div
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: 36,
                height: 36,
                borderRadius: '8px',
                background: 'linear-gradient(135deg, #52c41a 0%, #389e0d 100%)',
                boxShadow: '0 4px 12px rgba(82, 196, 26, 0.3)',
              }}
            >
              <PlusOutlined style={{ color: '#fff', fontSize: '18px' }} />
            </div>
            <span
              style={{
                background: 'linear-gradient(135deg, #52c41a 0%, #389e0d 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              创建新用户
            </span>
          </Space>
        }
        open={visible}
        onOpenChange={(open) => {
          if (!open) {
            setAvatarUrl('');
            setPasswordStrength(0);
          }
          onVisibleChange(open);
        }}
        modalProps={{
          destroyOnHidden: true,
          width: 680,
          styles: {
            body: {
              padding: '24px',
            },
          },
        }}
        onFinish={async (values) => {
          const success = await onFinish({
            ...values,
            userAvatar: avatarUrl || undefined,
          });
          if (success) {
            setAvatarUrl('');
            setPasswordStrength(0);
          }
          return success;
        }}
        layout="horizontal"
        labelCol={{ span: 6 }}
        wrapperCol={{ span: 16 }}
      >
        <div
          className="create-card"
          style={{
            padding: '16px',
            background: 'linear-gradient(135deg, #f6ffed 0%, #d9f7be 100%)',
            border: '1px solid #b7eb8f',
            borderRadius: '12px',
            marginBottom: '24px',
          }}
        >
          <Space direction="vertical" size={8} style={{ width: '100%' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <Space>
                <InfoCircleOutlined style={{ fontSize: '18px', color: '#52c41a' }} />
                <Text strong style={{ fontSize: '15px', color: '#262626' }}>
                  创建新用户账号
                </Text>
              </Space>
              <Tag color="success" style={{ borderRadius: '8px', fontSize: '12px' }}>
                新建
              </Tag>
            </div>
          </Space>
        </div>

        {/* 头像上传 */}
        <div className="avatar-section" style={{ marginBottom: '24px' }}>
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#52c41a', marginTop: 0 }}
          >
            <Space>
              <IdcardOutlined />
              <span>用户头像</span>
            </Space>
          </Divider>
          <div style={{ display: 'flex', justifyContent: 'center', marginTop: '20px' }}>
            <Upload showUploadList={false} beforeUpload={onAvatarUpload} accept="image/*">
              <div className="avatar-upload-wrapper">
                <Spin spinning={uploading}>
                  <Avatar
                    src={avatarUrl}
                    size={120}
                    icon={<UserOutlined />}
                    style={{
                      border: '3px solid #52c41a',
                      boxShadow: '0 4px 16px rgba(82, 196, 26, 0.3)',
                      backgroundColor: avatarUrl ? 'transparent' : '#f0f0f0',
                    }}
                  />
                </Spin>
                {!uploading && (
                  <div className="avatar-mask">
                    <CameraOutlined className="camera-icon" />
                    <div>点击上传头像</div>
                  </div>
                )}
              </div>
            </Upload>
          </div>
          <div style={{ textAlign: 'center', marginTop: '12px' }}>
            <Text type="secondary" style={{ fontSize: '12px' }}>
              {uploading
                ? '正在上传头像...'
                : '支持 JPG、PNG、GIF 格式，文件大小不超过 2MB（可选）'}
            </Text>
          </div>
        </div>

        {/* 账号信息 */}
        <div className="info-section" style={{ marginBottom: '24px' }}>
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#52c41a' }}
          >
            <Space>
              <KeyOutlined />
              <span>账号信息</span>
            </Space>
          </Divider>
          <ProFormText
            name="userAccount"
            label="登录账号"
            placeholder="请输入登录账号"
            rules={[
              { required: true, message: '请输入登录账号' },
              { min: 4, max: 16, message: '登录账号长度必须在4-16位之间' },
              { pattern: /^\w+$/, message: '登录账号只能包含字母、数字和下划线' },
            ]}
            fieldProps={{
              id: 'create-userAccount',
              prefix: <UserOutlined style={{ color: '#52c41a' }} />,
              style: { borderRadius: '8px' },
            }}
          />
          <ProFormText
            name="planetCode"
            label="星球编号"
            placeholder="请输入星球编号"
            rules={[
              { required: true, message: '请输入星球编号' },
              { max: 6, message: '星球编号长度不能超过6位' },
            ]}
            fieldProps={{
              id: 'create-planetCode',
              prefix: <IdcardOutlined style={{ color: '#52c41a' }} />,
              style: { borderRadius: '8px' },
            }}
          />
        </div>

        {/* 密码设置 */}
        <div className="info-section" style={{ marginBottom: '24px' }}>
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#52c41a' }}
          >
            <Space>
              <LockOutlined />
              <span>密码设置</span>
            </Space>
          </Divider>
          <Alert
            message="密码强度要求"
            description="密码必须包含大写字母、小写字母、数字和特殊字符，长度8-20位"
            type="info"
            showIcon
            style={{ marginBottom: '16px', borderRadius: '8px' }}
          />
          <ProFormText.Password
            name="userPassword"
            label="登录密码"
            placeholder="请输入登录密码"
            rules={[
              { required: true, message: '请输入登录密码' },
              { min: 8, max: 20, message: '登录密码长度必须在8-20位之间' },
              {
                pattern:
                  /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[~`!@#$%^&*()\-_=+[{\]}\\|;:'",<.>/?])[A-Za-z\d~`!@#$%^&*()\-_=+[{\]}\\|;:'",<.>/?]{8,20}$/,
                message: '密码必须包含大写字母、小写字母、数字和特殊字符',
              },
            ]}
            fieldProps={{
              id: 'create-userPassword',
              prefix: <LockOutlined style={{ color: '#52c41a' }} />,
              style: { borderRadius: '8px' },
              onChange: (e) => {
                const strength = calculatePasswordStrength(e.target.value);
                setPasswordStrength(strength);
              },
            }}
          />
          {passwordStrength > 0 && (
            <div style={{ marginBottom: '16px', marginLeft: '25%' }}>
              <Space>
                <Text type="secondary" style={{ fontSize: '12px' }}>
                  密码强度:
                </Text>
                <Text
                  strong
                  style={{ fontSize: '12px', color: getPasswordStrengthColor(passwordStrength) }}
                >
                  {getPasswordStrengthText(passwordStrength)}
                </Text>
              </Space>
              <div className="password-strength-bar">
                <div
                  className="password-strength-fill"
                  style={{
                    width: `${passwordStrength}%`,
                    backgroundColor: getPasswordStrengthColor(passwordStrength),
                  }}
                />
              </div>
            </div>
          )}
          <ProFormText.Password
            name="checkPassword"
            label="确认密码"
            placeholder="请再次输入登录密码"
            dependencies={['userPassword']}
            rules={[
              { required: true, message: '请再次输入登录密码' },
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (!value || getFieldValue('userPassword') === value) {
                    return Promise.resolve();
                  }
                  return Promise.reject(new Error('两次输入的密码不一致'));
                },
              }),
            ]}
            fieldProps={{
              id: 'create-checkPassword',
              prefix: <LockOutlined style={{ color: '#52c41a' }} />,
              style: { borderRadius: '8px' },
            }}
          />
        </div>

        {/* 基本信息 */}
        <div className="info-section" style={{ marginBottom: '24px' }}>
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#52c41a' }}
          >
            <Space>
              <UserOutlined />
              <span>基本信息</span>
            </Space>
          </Divider>
          <ProFormText
            name="userName"
            label="用户昵称"
            placeholder="请输入用户昵称（默认为登录账号）"
            rules={[{ max: 20, message: '用户昵称不能超过20个字符' }]}
            fieldProps={{
              id: 'create-userName',
              prefix: <UserOutlined style={{ color: '#52c41a' }} />,
              style: { borderRadius: '8px' },
            }}
          />
          <ProFormRadio.Group
            name="userGender"
            label="性别"
            initialValue={2}
            fieldProps={{
              id: 'create-userGender',
            }}
            options={[
              {
                label: (
                  <Space>
                    <WomanOutlined style={{ color: '#eb2f96' }} />
                    <span>女</span>
                  </Space>
                ),
                value: 0,
              },
              {
                label: (
                  <Space>
                    <ManOutlined style={{ color: '#1890ff' }} />
                    <span>男</span>
                  </Space>
                ),
                value: 1,
              },
              {
                label: (
                  <Space>
                    <UserOutlined style={{ color: '#8c8c8c' }} />
                    <span>未知</span>
                  </Space>
                ),
                value: 2,
              },
            ]}
          />
          <ProFormTextArea
            name="userProfile"
            label="个人简介"
            placeholder="请输入个人简介"
            fieldProps={{
              id: 'create-userProfile',
              maxLength: 200,
              showCount: true,
              autoSize: { minRows: 3, maxRows: 5 },
              style: { borderRadius: '8px' },
            }}
            rules={[{ max: 200, message: '个人简介不能超过200个字符' }]}
          />
        </div>

        {/* 联系方式 */}
        <div className="info-section" style={{ marginBottom: '24px' }}>
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#52c41a' }}
          >
            <Space>
              <PhoneOutlined />
              <span>联系方式</span>
            </Space>
          </Divider>
          <ProFormText
            name="userPhone"
            label="手机号"
            placeholder="请输入11位手机号"
            rules={[
              {
                pattern: /^1[3-9]\d{9}$/,
                message: '手机号格式不正确',
              },
            ]}
            fieldProps={{
              id: 'create-userPhone',
              prefix: <PhoneOutlined style={{ color: '#52c41a' }} />,
              style: { borderRadius: '8px' },
            }}
          />
          <ProFormText
            name="userEmail"
            label="邮箱地址"
            placeholder="请输入邮箱地址"
            rules={[
              {
                type: 'email',
                message: '邮箱格式不正确',
              },
            ]}
            fieldProps={{
              id: 'create-userEmail',
              prefix: <MailOutlined style={{ color: '#52c41a' }} />,
              style: { borderRadius: '8px' },
            }}
          />
        </div>

        {/* 账号类型 */}
        <div className="info-section">
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#52c41a' }}
          >
            <Space>
              <TeamOutlined />
              <span>账号类型</span>
            </Space>
          </Divider>
          <ProFormRadio.Group
            name="userRole"
            label="用户角色"
            initialValue="user"
            fieldProps={{
              id: 'create-userRole',
            }}
            options={[
              { label: '普通用户', value: 'user' },
              { label: '管理员', value: 'admin' },
            ]}
          />
          <div
            style={{
              padding: '12px 16px',
              background: '#fff7e6',
              border: '1px solid #ffd591',
              borderRadius: '8px',
              marginTop: '12px',
            }}
          >
            <Space>
              <SafetyOutlined style={{ color: '#faad14' }} />
              <Text type="warning" style={{ fontSize: '13px' }}>
                管理员拥有系统最高权限，请谨慎授予
              </Text>
            </Space>
          </div>
        </div>
      </ModalForm>
    </>
  );
};

export default CreateUserModal;

// user-center-vue-frontend/src/views/admin/modules/create-user-modal.vue
<template>
    <a-modal
        :confirm-loading="submitting"
        :mask-closable="false"
        :ok-button-props="{ loading: submitting, disabled: uploading }"
        :open="visible"
        destroy-on-close
        title="创建新用户"
        width="720px"
        @cancel="handleCancel"
        @ok="handleSubmit"
    >
        <div class="modal-header-card">
            <a-space>
                <PlusOutlined class="header-icon" />
                <div class="header-text">
                    <strong>创建新用户账号</strong>
                    <span>请填写账号信息并为新用户设置初始密码</span>
                </div>
            </a-space>
        </div>

        <div class="section">
            <a-divider orientation="left">
                <a-space>
                    <IdcardOutlined />
                    <span>用户头像</span>
                </a-space>
            </a-divider>
            <div class="avatar-wrapper">
                <a-upload
                    :before-upload="beforeAvatarUpload"
                    :disabled="uploading"
                    :show-upload-list="false"
                    accept="image/*"
                >
                    <div class="avatar-upload">
                        <a-spin :spinning="uploading">
                            <a-avatar :size="120" :src="avatarUrl">
                                <template #icon>
                                    <UserOutlined />
                                </template>
                            </a-avatar>
                        </a-spin>
                        <div class="avatar-mask">
                            <CameraOutlined />
                            <span>{{ uploading ? "上传中..." : "点击上传头像" }}</span>
                        </div>
                    </div>
                </a-upload>
                <a-typography-text class="avatar-tip" type="secondary">
                    支持 JPG、PNG、GIF 格式，文件大小不超过 2MB
                </a-typography-text>
            </div>
        </div>

        <a-form
            ref="formRef"
            :label-col="labelCol"
            :model="formModel"
            :rules="rules"
            :wrapper-col="wrapperCol"
            autocomplete="off"
            layout="horizontal"
        >
            <div class="section">
                <a-divider orientation="left">
                    <a-space>
                        <KeyOutlined />
                        <span>账号信息</span>
                    </a-space>
                </a-divider>
                <a-form-item label="登录账号" name="userAccount">
                    <a-input
                        v-model:value="formModel.userAccount"
                        allow-clear
                        class="rounded-input"
                        placeholder="请输入登录账号"
                    >
                        <template #prefix>
                            <UserOutlined />
                        </template>
                    </a-input>
                </a-form-item>
                <a-form-item label="星球编号" name="planetCode">
                    <a-input
                        v-model:value="formModel.planetCode"
                        allow-clear
                        class="rounded-input"
                        placeholder="请输入星球编号"
                    >
                        <template #prefix>
                            <IdcardOutlined />
                        </template>
                    </a-input>
                </a-form-item>
            </div>

            <div class="section">
                <a-divider orientation="left">
                    <a-space>
                        <LockOutlined />
                        <span>密码设置</span>
                    </a-space>
                </a-divider>
                <a-alert
                    class="password-alert"
                    message="密码须包含大小写字母、数字和特殊字符，长度 8-20 位"
                    show-icon
                    type="info"
                />
                <a-form-item label="登录密码" name="userPassword">
                    <a-input-password
                        v-model:value="formModel.userPassword"
                        allow-clear
                        class="rounded-input"
                        placeholder="请输入登录密码"
                    >
                        <template #prefix>
                            <LockOutlined />
                        </template>
                    </a-input-password>
                </a-form-item>
                <div v-if="passwordStrength > 0" class="password-strength">
                    <a-space>
                        <span>密码强度：</span>
                        <a-tag :color="passwordStrengthColor">{{ passwordStrengthText }}</a-tag>
                    </a-space>
                    <div class="strength-bar">
                        <div :style="passwordStrengthStyle" class="strength-fill"></div>
                    </div>
                </div>
                <a-form-item label="确认密码" name="checkPassword">
                    <a-input-password
                        v-model:value="formModel.checkPassword"
                        allow-clear
                        class="rounded-input"
                        placeholder="请再次输入密码"
                    >
                        <template #prefix>
                            <SafetyOutlined />
                        </template>
                    </a-input-password>
                </a-form-item>
            </div>

            <div class="section">
                <a-divider orientation="left">
                    <a-space>
                        <UserOutlined />
                        <span>基本信息</span>
                    </a-space>
                </a-divider>
                <a-form-item label="用户昵称" name="userName">
                    <a-input
                        v-model:value="formModel.userName"
                        allow-clear
                        class="rounded-input"
                        placeholder="请输入用户昵称"
                    >
                        <template #prefix>
                            <UserOutlined />
                        </template>
                    </a-input>
                </a-form-item>
                <a-form-item label="用户角色" name="userRole">
                    <a-radio-group v-model:value="formModel.userRole">
                        <a-radio value="user"> <TeamOutlined /> 普通用户 </a-radio>
                        <a-radio value="admin"> <SafetyOutlined /> 管理员 </a-radio>
                    </a-radio-group>
                </a-form-item>
                <a-form-item label="性别" name="userGender">
                    <a-radio-group v-model:value="formModel.userGender">
                        <a-radio :value="0">女</a-radio>
                        <a-radio :value="1">男</a-radio>
                        <a-radio :value="2">未知</a-radio>
                    </a-radio-group>
                </a-form-item>
                <a-form-item label="手机号码" name="userPhone">
                    <a-input
                        v-model:value="formModel.userPhone"
                        allow-clear
                        class="rounded-input"
                        placeholder="请输入手机号码"
                    >
                        <template #prefix>
                            <PhoneOutlined />
                        </template>
                    </a-input>
                </a-form-item>
                <a-form-item label="邮箱地址" name="userEmail">
                    <a-input
                        v-model:value="formModel.userEmail"
                        allow-clear
                        class="rounded-input"
                        placeholder="请输入邮箱地址"
                    >
                        <template #prefix>
                            <MailOutlined />
                        </template>
                    </a-input>
                </a-form-item>
                <a-form-item label="个人简介" name="userProfile">
                    <a-textarea
                        v-model:value="formModel.userProfile"
                        :maxlength="200"
                        :rows="3"
                        placeholder="请输入个人简介"
                        show-count
                    />
                </a-form-item>
            </div>
        </a-form>
    </a-modal>
</template>

<script lang="ts" setup>
import { computed, reactive, ref, watch } from "vue";
import type { FormInstance, UploadProps } from "ant-design-vue";
import type { Rule } from "ant-design-vue/es/form";
import {
    CameraOutlined,
    IdcardOutlined,
    KeyOutlined,
    LockOutlined,
    MailOutlined,
    PhoneOutlined,
    PlusOutlined,
    SafetyOutlined,
    TeamOutlined,
    UserOutlined,
} from "@ant-design/icons-vue";
import { useUserOperations } from "@/views/admin/hooks/useUserOperations";
import { PASSWORD_PATTERN } from "@/constants/validation";

const props = defineProps<{
    visible: boolean;
}>();

const emit = defineEmits<{
    (event: "update:visible", value: boolean): void;
    (event: "success"): void;
}>();

const { handleAdd, handleAvatarUpload: uploadAvatarHandler, uploading } = useUserOperations();

const labelCol = { span: 6 };
const wrapperCol = { span: 16 };

const defaultFormState: API.AdminAddUserRequest & { checkPassword: string } = {
    userAccount: "",
    userPassword: "",
    checkPassword: "",
    planetCode: "",
    userName: "",
    userAvatar: undefined,
    userProfile: "",
    userRole: "user",
    userGender: 2,
    userPhone: "",
    userEmail: "",
};

const formModel = reactive({ ...defaultFormState });
const formRef = ref<FormInstance>();
const submitting = ref(false);
const avatarUrl = ref<string>("");
const passwordStrength = ref(0);

const rules: Record<string, Rule[]> = {
    userAccount: [
        { required: true, message: "请输入登录账号", trigger: ["blur", "change"] },
        { min: 4, max: 16, message: "登录账号长度必须在 4-16 位之间", trigger: ["blur", "change"] },
        {
            pattern: /^\w+$/,
            message: "登录账号只能包含字母、数字和下划线",
            trigger: ["blur", "change"],
        },
    ],
    planetCode: [
        { required: true, message: "请输入星球编号", trigger: ["blur", "change"] },
        { max: 6, message: "星球编号长度不能超过 6 位", trigger: ["blur", "change"] },
    ],
    userPassword: [
        { required: true, message: "请输入登录密码", trigger: "blur" },
        { min: 8, max: 20, message: "密码长度必须在 8-20 位之间", trigger: ["blur", "change"] },
        {
            pattern: PASSWORD_PATTERN,
            message: "密码需包含大小写字母、数字和特殊字符",
            trigger: ["blur", "change"],
        },
    ],
    checkPassword: [
        { required: true, message: "请确认登录密码", trigger: "blur" },
        {
            validator: (_rule, value) => {
                if (!value || value === formModel.userPassword) {
                    return Promise.resolve();
                }
                return Promise.reject(new Error("两次输入的密码不一致"));
            },
            trigger: ["blur", "change"],
        },
    ],
    userName: [{ max: 20, message: "用户昵称不能超过 20 个字符", trigger: ["blur", "change"] }],
    userPhone: [
        {
            validator: (_rule, value) => {
                if (!value) {
                    return Promise.resolve();
                }
                return /^1[3-9]\d{9}$/.test(value)
                    ? Promise.resolve()
                    : Promise.reject(new Error("手机号格式不正确"));
            },
            trigger: ["blur", "change"],
        },
    ],
    userEmail: [
        {
            type: "email",
            message: "邮箱格式不正确",
            trigger: ["blur", "change"],
        },
    ],
    userProfile: [
        { max: 200, message: "个人简介不能超过 200 个字符", trigger: ["blur", "change"] },
    ],
};

watch(
    () => formModel.userPassword,
    (value) => {
        passwordStrength.value = calculatePasswordStrength(value);
    }
);

watch(
    () => props.visible,
    (visible) => {
        if (!visible) {
            resetForm();
        }
    }
);

const passwordStrengthColor = computed(() => {
    if (passwordStrength.value < 40) return "#ff4d4f";
    if (passwordStrength.value < 70) return "#faad14";
    return "#52c41a";
});

const passwordStrengthText = computed(() => {
    if (passwordStrength.value < 40) return "弱";
    if (passwordStrength.value < 70) return "中";
    return "强";
});

const passwordStrengthStyle = computed(() => ({
    width: `${Math.max(passwordStrength.value, 10)}%`,
    backgroundColor: passwordStrengthColor.value,
}));

const calculatePasswordStrength = (password: string): number => {
    if (!password) {
        return 0;
    }
    let strength = 0;
    if (password.length >= 8) strength += 25;
    if (password.length >= 12) strength += 25;
    if (/[a-z]/.test(password)) strength += 12.5;
    if (/[A-Z]/.test(password)) strength += 12.5;
    if (/\d/.test(password)) strength += 12.5;
    if (/[~`!@#$%^&*()\-_=+[\]{}\\|;:'",<.>/?]/.test(password)) strength += 12.5;
    return Math.min(strength, 100);
};

const beforeAvatarUpload: UploadProps["beforeUpload"] = async (file) => {
    const rawFile = file as File;
    const url = await uploadAvatarHandler(rawFile);
    if (url) {
        avatarUrl.value = url;
    }
    return false;
};

const handleSubmit = async () => {
    if (submitting.value) {
        return;
    }
    try {
        submitting.value = true;
        await formRef.value?.validate();
        const payload: API.AdminAddUserRequest = {
            userAccount: formModel.userAccount.trim(),
            userPassword: formModel.userPassword,
            checkPassword: formModel.checkPassword,
            planetCode: formModel.planetCode.trim(),
            userName: formModel.userName?.trim() || undefined,
            userAvatar: avatarUrl.value || undefined,
            userProfile: formModel.userProfile?.trim() || undefined,
            userRole: formModel.userRole,
            userGender: formModel.userGender as 0 | 1 | 2,
            userPhone: formModel.userPhone?.trim() || undefined,
            userEmail: formModel.userEmail?.trim() || undefined,
        };

        const success = await handleAdd(payload);
        if (success) {
            emit("success");
            emit("update:visible", false);
            resetForm();
        }
    } finally {
        submitting.value = false;
    }
};

const handleCancel = () => {
    emit("update:visible", false);
};

const resetForm = () => {
    Object.assign(formModel, defaultFormState);
    avatarUrl.value = "";
    passwordStrength.value = 0;
    formRef.value?.resetFields();
    formRef.value?.clearValidate();
};
</script>

<style scoped>
.modal-header-card {
    padding: 16px;
    margin-bottom: 16px;
    background: linear-gradient(135deg, #f6ffed 0%, #d9f7be 100%);
    border: 1px solid #b7eb8f;
    border-radius: 12px;
}

.header-icon {
    font-size: 24px;
    color: #389e0d;
}

.header-text {
    display: flex;
    flex-direction: column;
    gap: 4px;
    font-size: 13px;
    color: rgb(0 0 0 / 65%);
}

.section {
    margin-bottom: 24px;
}

.avatar-wrapper {
    display: flex;
    flex-direction: column;
    gap: 12px;
    align-items: center;
    margin-top: 12px;
}

.avatar-upload {
    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
}

.avatar-mask {
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: 13px;
    color: #fff;
    background: rgb(0 0 0 / 45%);
    border-radius: 50%;
    opacity: 0;
    transition: opacity 0.3s ease;
}

.avatar-upload:hover .avatar-mask {
    opacity: 1;
}

.avatar-mask span {
    margin-top: 6px;
}

.avatar-tip {
    font-size: 12px;
}

.rounded-input :deep(.ant-input),
.rounded-input :deep(.ant-input-affix-wrapper) {
    border-radius: 8px;
}

.password-alert {
    margin-bottom: 16px;
    border-radius: 8px;
}

.password-strength {
    margin: -8px 0 16px 25%;
    color: rgb(0 0 0 / 65%);
}

.strength-bar {
    height: 4px;
    margin-top: 8px;
    overflow: hidden;
    background: #f0f0f0;
    border-radius: 2px;
}

.strength-fill {
    height: 100%;
    transition:
        width 0.3s ease,
        background-color 0.3s ease;
}
</style>
