// user-center-react-frontend/src/pages/admin/user-manage/components/EditUserModal.tsx
﻿import { ModalForm, ProFormRadio, ProFormText, ProFormTextArea } from '@ant-design/pro-components';
import {
  CameraOutlined,
  EditOutlined,
  IdcardOutlined,
  InfoCircleOutlined,
  MailOutlined,
  ManOutlined,
  PhoneOutlined,
  SafetyOutlined,
  TeamOutlined,
  UserOutlined,
  WomanOutlined,
} from '@ant-design/icons';
import { Avatar, Divider, Space, Spin, Tag, Typography, Upload } from 'antd';
import React, { useEffect, useState } from 'react';
import { useUserOperations } from '../hooks/useUserOperations';

const { Text } = Typography;

interface EditUserModalProps {
  visible: boolean;
  editingUser: API.User | null;
  onVisibleChange: (visible: boolean) => void;
  onFinish: (values: API.AdminUpdateUserInfoParams) => Promise<boolean>;
}

const EditUserModal: React.FC<EditUserModalProps> = ({
  visible,
  editingUser,
  onVisibleChange,
  onFinish,
}) => {
  const [avatarUrl, setAvatarUrl] = useState<string>('');
  const { handleAvatarUpload, handleUpdate, uploading } = useUserOperations();

  useEffect(() => {
    if (visible && editingUser) {
      setAvatarUrl(editingUser.userAvatar || '');
    } else if (!visible) {
      setAvatarUrl('');
    }
  }, [visible, editingUser]);

  /**
   * 处理头像上传
   * 流程:
   * 1. 上传文件到服务器
   * 2. 获取头像 URL
   * 3. 立即调用更新用户信息接口,将新头像 URL 保存到数据库
   * 4. 更新本地头像显示
   * 注意: 不关闭弹窗,用户可以继续编辑其他信息
   */
  const onAvatarUpload = async (file: File) => {
    if (!editingUser?.id) {
      return false;
    }

    // 步骤 1-2: 上传文件到服务器
    const url = await handleAvatarUpload(file);
    if (url) {
      // 步骤 3: 立即更新用户头像信息到数据库
      const success = await handleUpdate({
        id: editingUser.id,
        userAvatar: url, // 使用新上传的头像 URL
      });

      if (success) {
        // 步骤 4: 更新本地头像显示,同时更新 editingUser 的头像 URL
        setAvatarUrl(url);
        // 更新 editingUser 对象中的头像,确保后续操作使用新的头像 URL
        if (editingUser) {
          editingUser.userAvatar = url;
        }
        // 注意: 不调用 onFinish,保持弹窗打开,用户可以继续编辑其他信息
      }
    }
    return false; // 阻止 Upload 组件的自动上传行为
  };

  return (
    <>
      <style>{`
        @keyframes slideInFromTop {
          from {
            opacity: 0;
            transform: translateY(-20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        @keyframes fadeIn {
          from {
            opacity: 0;
          }
          to {
            opacity: 1;
          }
        }
        @keyframes scaleIn {
          from {
            opacity: 0;
            transform: scale(0.9);
          }
          to {
            opacity: 1;
            transform: scale(1);
          }
        }
        .edit-card {
          animation: slideInFromTop 0.5s ease-out;
        }
        .info-section {
          animation: fadeIn 0.6s ease-out;
        }
        .avatar-section {
          animation: scaleIn 0.5s ease-out;
        }
        .avatar-upload-wrapper {
          position: relative;
          display: inline-block;
          cursor: pointer;
        }
        .avatar-upload-wrapper:hover .avatar-mask {
          opacity: 1;
        }
        .avatar-mask {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          background: rgba(0, 0, 0, 0.5);
          border-radius: 50%;
          opacity: 0;
          transition: opacity 0.3s;
          color: #fff;
          font-size: 14px;
        }
        .avatar-mask .camera-icon {
          font-size: 24px;
          margin-bottom: 8px;
        }
      `}</style>
      <ModalForm<API.AdminUpdateUserInfoParams>
        title={
          <Space style={{ fontSize: '16px', fontWeight: 600 }}>
            <div
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: 36,
                height: 36,
                borderRadius: '8px',
                background: 'linear-gradient(135deg, #1890ff 0%, #096dd9 100%)',
                boxShadow: '0 4px 12px rgba(24, 144, 255, 0.3)',
              }}
            >
              <EditOutlined style={{ color: '#fff', fontSize: '18px' }} />
            </div>
            <span
              style={{
                background: 'linear-gradient(135deg, #1890ff 0%, #096dd9 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              编辑用户信息
            </span>
          </Space>
        }
        open={visible}
        onOpenChange={onVisibleChange}
        modalProps={{
          destroyOnHidden: true,
          width: 680,
          styles: {
            body: {
              padding: '24px',
            },
          },
        }}
        onFinish={async (values) => {
          const success = await onFinish({
            ...values,
            id: editingUser?.id || '',
            userAvatar: avatarUrl || editingUser?.userAvatar || '',
          });
          return success;
        }}
        layout="horizontal"
        labelCol={{ span: 6 }}
        wrapperCol={{ span: 16 }}
        request={async () => {
          if (!editingUser) {
            setAvatarUrl('');
            return {
              id: '',
              userName: '',
              userRole: 'user',
              userGender: 2,
              userPhone: '',
              userEmail: '',
              userAvatar: '',
              userProfile: '',
            };
          }
          setAvatarUrl(editingUser.userAvatar || '');
          return {
            id: editingUser.id,
            userName: editingUser.userName,
            userRole: editingUser.userRole,
            userGender: editingUser.userGender,
            userPhone: editingUser.userPhone,
            userEmail: editingUser.userEmail,
            userAvatar: editingUser.userAvatar,
            userProfile: editingUser.userProfile,
          };
        }}
      >
        {editingUser && (
          <div
            className="edit-card"
            style={{
              padding: '16px',
              background: 'linear-gradient(135deg, #e6f7ff 0%, #bae7ff 100%)',
              border: '1px solid #91d5ff',
              borderRadius: '12px',
              marginBottom: '24px',
            }}
          >
            <Space direction="vertical" size={8} style={{ width: '100%' }}>
              <div
                style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}
              >
                <Space>
                  <InfoCircleOutlined style={{ fontSize: '18px', color: '#1890ff' }} />
                  <Text strong style={{ fontSize: '15px', color: '#262626' }}>
                    编辑用户
                  </Text>
                </Space>
                <Tag color="processing" style={{ borderRadius: '8px', fontSize: '12px' }}>
                  账号：{editingUser.userAccount}
                </Tag>
              </div>
            </Space>
          </div>
        )}
        <div className="avatar-section" style={{ marginBottom: '24px' }}>
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#1890ff', marginTop: 0 }}
          >
            <Space>
              <IdcardOutlined />
              <span>用户头像</span>
            </Space>
          </Divider>
          <div style={{ display: 'flex', justifyContent: 'center', marginTop: '20px' }}>
            <Upload showUploadList={false} beforeUpload={onAvatarUpload} accept="image/*">
              <div className="avatar-upload-wrapper">
                <Spin spinning={uploading}>
                  <Avatar
                    src={avatarUrl}
                    size={120}
                    icon={<UserOutlined />}
                    style={{
                      border: '3px solid #1890ff',
                      boxShadow: '0 4px 16px rgba(24, 144, 255, 0.3)',
                      backgroundColor: avatarUrl ? 'transparent' : '#f0f0f0',
                    }}
                  />
                </Spin>
                {!uploading && (
                  <div className="avatar-mask">
                    <CameraOutlined className="camera-icon" />
                    <div>点击上传头像</div>
                  </div>
                )}
              </div>
            </Upload>
          </div>
          <div style={{ textAlign: 'center', marginTop: '12px' }}>
            <Text type="secondary" style={{ fontSize: '12px' }}>
              {uploading ? '正在上传头像...' : '支持 JPG、PNG、GIF 格式，文件大小不超过 5MB'}
            </Text>
          </div>
        </div>
        <div className="info-section" style={{ marginBottom: '24px' }}>
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#1890ff' }}
          >
            <Space>
              <UserOutlined />
              <span>基本信息</span>
            </Space>
          </Divider>
          <ProFormText
            name="userName"
            label="用户昵称"
            placeholder="请输入用户昵称"
            rules={[
              { required: true, message: '请输入用户昵称' },
              { max: 20, message: '用户昵称不能超过20个字符' },
            ]}
            fieldProps={{
              prefix: <UserOutlined style={{ color: '#1890ff' }} />,
              style: { borderRadius: '8px' },
            }}
          />
          <ProFormRadio.Group
            name="userGender"
            label="性别"
            options={[
              {
                label: (
                  <Space>
                    <WomanOutlined style={{ color: '#eb2f96' }} />
                    <span>女</span>
                  </Space>
                ),
                value: 0,
              },
              {
                label: (
                  <Space>
                    <ManOutlined style={{ color: '#1890ff' }} />
                    <span>男</span>
                  </Space>
                ),
                value: 1,
              },
              {
                label: (
                  <Space>
                    <UserOutlined style={{ color: '#8c8c8c' }} />
                    <span>未知</span>
                  </Space>
                ),
                value: 2,
              },
            ]}
          />
          <ProFormTextArea
            name="userProfile"
            label="个人简介"
            placeholder="请输入个人简介"
            fieldProps={{
              maxLength: 200,
              showCount: true,
              autoSize: { minRows: 3, maxRows: 5 },
              style: { borderRadius: '8px' },
            }}
            rules={[{ max: 200, message: '个人简介不能超过200个字符' }]}
          />
        </div>
        <div className="info-section" style={{ marginBottom: '24px' }}>
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#1890ff' }}
          >
            <Space>
              <PhoneOutlined />
              <span>联系方式</span>
            </Space>
          </Divider>
          <ProFormText
            name="userPhone"
            label="手机号"
            placeholder="请输入11位手机号"
            rules={[
              {
                pattern: /^1[3-9]\d{9}$/,
                message: '手机号格式不正确',
              },
            ]}
            fieldProps={{
              prefix: <PhoneOutlined style={{ color: '#1890ff' }} />,
              style: { borderRadius: '8px' },
            }}
          />
          <ProFormText
            name="userEmail"
            label="邮箱地址"
            placeholder="请输入邮箱地址"
            rules={[
              {
                type: 'email',
                message: '邮箱格式不正确',
              },
            ]}
            fieldProps={{
              prefix: <MailOutlined style={{ color: '#1890ff' }} />,
              style: { borderRadius: '8px' },
            }}
          />
        </div>
        <div className="info-section">
          <Divider
            orientation="left"
            style={{ fontSize: '14px', fontWeight: 600, color: '#1890ff' }}
          >
            <Space>
              <TeamOutlined />
              <span>账号类型</span>
            </Space>
          </Divider>
          <ProFormRadio.Group
            name="userRole"
            label="用户角色"
            options={[
              { label: '普通用户', value: 'user' },
              { label: '管理员', value: 'admin' },
            ]}
          />
          <div
            style={{
              padding: '12px 16px',
              background: '#fff7e6',
              border: '1px solid #ffd591',
              borderRadius: '8px',
              marginTop: '12px',
            }}
          >
            <Space>
              <SafetyOutlined style={{ color: '#faad14' }} />
              <Text type="warning" style={{ fontSize: '13px' }}>
                管理员拥有系统最高权限,请谨慎授予
              </Text>
            </Space>
          </div>
        </div>
      </ModalForm>
    </>
  );
};

export default EditUserModal;

// user-center-vue-frontend/src/views/admin/modules/edit-user-modal.vue
<template>
    <a-modal
        :open="visible"
        title="编辑用户信息"
        width="720px"
        :confirm-loading="submitting"
        :ok-button-props="{ disabled: !user, loading: submitting || uploading }"
        :mask-closable="false"
        destroy-on-close
        @cancel="handleCancel"
        @ok="handleSubmit"
    >
        <div v-if="user" class="modal-header-card">
            <a-space>
                <EditOutlined class="header-icon" />
                <div class="header-text">
                    <strong>账号：{{ user.userAccount }}</strong>
                    <span>创建时间：{{ formatCreateTime(user.createTime) }}</span>
                </div>
            </a-space>
        </div>

        <div class="section">
            <a-divider orientation="left">
                <a-space>
                    <IdcardOutlined />
                    <span>用户头像</span>
                </a-space>
            </a-divider>
            <div class="avatar-wrapper">
                <a-upload
                    :show-upload-list="false"
                    accept="image/*"
                    :before-upload="beforeAvatarUpload"
                    :disabled="uploading || !user"
                >
                    <div class="avatar-upload">
                        <a-spin :spinning="uploading">
                            <a-avatar :size="120" :src="avatarUrl">
                                <template #icon>
                                    <UserOutlined />
                                </template>
                            </a-avatar>
                        </a-spin>
                        <div class="avatar-mask">
                            <CameraOutlined />
                            <span>{{ uploading ? "上传中..." : "点击更换头像" }}</span>
                        </div>
                    </div>
                </a-upload>
                <a-typography-text type="secondary" class="avatar-tip">
                    上传后会立即保存，刷新后生效
                </a-typography-text>
            </div>
        </div>

        <a-form
            ref="formRef"
            :model="formModel"
            :rules="rules"
            layout="horizontal"
            :label-col="labelCol"
            :wrapper-col="wrapperCol"
            autocomplete="off"
        >
            <div class="section">
                <a-divider orientation="left">
                    <a-space>
                        <UserOutlined />
                        <span>基本信息</span>
                    </a-space>
                </a-divider>
                <a-form-item label="用户昵称" name="userName">
                    <a-input
                        v-model:value="formModel.userName"
                        placeholder="请输入用户昵称"
                        allow-clear
                        class="rounded-input"
                    >
                        <template #prefix>
                            <UserOutlined />
                        </template>
                    </a-input>
                </a-form-item>
                <a-form-item label="用户角色" name="userRole">
                    <a-radio-group v-model:value="formModel.userRole">
                        <a-radio value="user"> <TeamOutlined /> 普通用户 </a-radio>
                        <a-radio value="admin"> <SafetyOutlined /> 管理员 </a-radio>
                    </a-radio-group>
                </a-form-item>
                <a-form-item label="性别" name="userGender">
                    <a-radio-group v-model:value="formModel.userGender">
                        <a-radio :value="0">女</a-radio>
                        <a-radio :value="1">男</a-radio>
                        <a-radio :value="2">未知</a-radio>
                    </a-radio-group>
                </a-form-item>
                <a-form-item label="个人简介" name="userProfile">
                    <a-textarea
                        v-model:value="formModel.userProfile"
                        :rows="3"
                        :maxlength="200"
                        show-count
                        placeholder="请输入个人简介"
                    />
                </a-form-item>
            </div>

            <div class="section">
                <a-divider orientation="left">
                    <a-space>
                        <PhoneOutlined />
                        <span>联系方式</span>
                    </a-space>
                </a-divider>
                <a-form-item label="手机号码" name="userPhone">
                    <a-input
                        v-model:value="formModel.userPhone"
                        placeholder="请输入手机号码"
                        allow-clear
                        class="rounded-input"
                    >
                        <template #prefix>
                            <PhoneOutlined />
                        </template>
                    </a-input>
                </a-form-item>
                <a-form-item label="邮箱地址" name="userEmail">
                    <a-input
                        v-model:value="formModel.userEmail"
                        placeholder="请输入邮箱地址"
                        allow-clear
                        class="rounded-input"
                    >
                        <template #prefix>
                            <MailOutlined />
                        </template>
                    </a-input>
                </a-form-item>
            </div>
        </a-form>
    </a-modal>
</template>

<script setup lang="ts">
import dayjs from "dayjs";
import { computed, reactive, ref, watch } from "vue";
import type { FormInstance, UploadProps } from "ant-design-vue";
import type { Rule } from "ant-design-vue/es/form";
import {
    EditOutlined,
    IdcardOutlined,
    UserOutlined,
    TeamOutlined,
    SafetyOutlined,
    PhoneOutlined,
    MailOutlined,
    CameraOutlined,
} from "@ant-design/icons-vue";
import { USER_ROLE } from "@/constants/system";
import { useUserOperations } from "@/views/admin/hooks/useUserOperations";

const props = defineProps<{
    visible: boolean;
    user: API.User | null;
}>();

const emit = defineEmits<{
    (event: "update:visible", value: boolean): void;
    (event: "success"): void;
}>();

const labelCol = { span: 6 };
const wrapperCol = { span: 16 };

type UserRole = (typeof USER_ROLE)[keyof typeof USER_ROLE];

const formRef = ref<FormInstance>();
const formModel = reactive({
    userName: "",
    userRole: USER_ROLE.USER as UserRole,
    userGender: 2 as 0 | 1 | 2,
    userProfile: "",
    userPhone: "",
    userEmail: "",
});
const avatarUrl = ref<string>("");
const submitting = ref(false);

const rules: Record<string, Rule[]> = {
    userName: [
        { required: true, message: "请输入用户昵称", trigger: "blur" },
        { max: 20, message: "用户昵称不能超过 20 个字符", trigger: ["blur", "change"] },
    ],
    userProfile: [
        { max: 200, message: "个人简介不能超过 200 个字符", trigger: ["blur", "change"] },
    ],
    userPhone: [
        {
            validator: (_rule, value) => {
                if (!value) {
                    return Promise.resolve();
                }
                return /^1[3-9]\d{9}$/.test(value)
                    ? Promise.resolve()
                    : Promise.reject(new Error("手机号格式不正确"));
            },
            trigger: ["blur", "change"],
        },
    ],
    userEmail: [
        {
            type: "email",
            message: "邮箱格式不正确",
            trigger: ["blur", "change"],
        },
    ],
};

const { handleUpdate, handleAvatarUpload: uploadAvatarHandler, uploading } = useUserOperations();

const passwordlessUser = computed(() => props.user);

watch(
    () => props.visible,
    (visible) => {
        if (visible) {
            populateForm();
        } else {
            resetForm();
        }
    }
);

watch(passwordlessUser, () => {
    if (props.visible) {
        populateForm();
    }
});

const populateForm = () => {
    if (!props.user) {
        return;
    }
    formModel.userName = props.user.userName ?? "";
    formModel.userRole = (props.user.userRole ?? USER_ROLE.USER) as UserRole;
    formModel.userGender = (props.user.userGender ?? 2) as 0 | 1 | 2;
    formModel.userProfile = props.user.userProfile ?? "";
    formModel.userPhone = props.user.userPhone ?? "";
    formModel.userEmail = props.user.userEmail ?? "";
    avatarUrl.value = props.user.userAvatar ?? "";
    formRef.value?.clearValidate();
};

const beforeAvatarUpload: UploadProps["beforeUpload"] = async (file) => {
    if (!props.user?.id) {
        return false;
    }
    const rawFile = file as File;
    const url = await uploadAvatarHandler(rawFile);
    if (url) {
        const success = await handleUpdate({ id: props.user.id, userAvatar: url });
        if (success) {
            avatarUrl.value = url;
            emit("success");
        }
    }
    return false;
};

const handleSubmit = async () => {
    if (!props.user?.id || submitting.value) {
        return;
    }
    try {
        submitting.value = true;
        await formRef.value?.validate();
        const payload: API.AdminUpdateUserInfoRequest = {
            id: props.user.id,
            userName: formModel.userName.trim(),
            userRole: formModel.userRole,
            userGender: formModel.userGender,
            userProfile: formModel.userProfile.trim() || undefined,
            userPhone: formModel.userPhone.trim() || undefined,
            userEmail: formModel.userEmail.trim() || undefined,
        };
        const success = await handleUpdate(payload);
        if (success) {
            emit("success");
            emit("update:visible", false);
        }
    } finally {
        submitting.value = false;
    }
};

const handleCancel = () => {
    emit("update:visible", false);
};

const resetForm = () => {
    formModel.userName = "";
    formModel.userRole = USER_ROLE.USER;
    formModel.userGender = 2;
    formModel.userProfile = "";
    formModel.userPhone = "";
    formModel.userEmail = "";
    avatarUrl.value = "";
    formRef.value?.resetFields();
    formRef.value?.clearValidate();
};

const formatCreateTime = (time?: string) => {
    if (!time) {
        return "";
    }
    return dayjs(time).format("YYYY-MM-DD HH:mm:ss");
};
</script>

<style scoped>
.modal-header-card {
    padding: 16px;
    margin-bottom: 16px;
    background: linear-gradient(135deg, #e6f7ff 0%, #bae7ff 100%);
    border: 1px solid #91d5ff;
    border-radius: 12px;
}

.header-icon {
    font-size: 24px;
    color: #1677ff;
}

.header-text {
    display: flex;
    flex-direction: column;
    gap: 4px;
    font-size: 13px;
    color: rgb(0 0 0 / 65%);
}

.section {
    margin-bottom: 24px;
}

.avatar-wrapper {
    display: flex;
    flex-direction: column;
    gap: 12px;
    align-items: center;
    margin-top: 12px;
}

.avatar-upload {
    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
}

.avatar-mask {
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: 13px;
    color: #fff;
    background: rgb(0 0 0 / 45%);
    border-radius: 50%;
    opacity: 0;
    transition: opacity 0.3s ease;
}

.avatar-upload:hover .avatar-mask {
    opacity: 1;
}

.avatar-tip {
    font-size: 12px;
}

.rounded-input :deep(.ant-input),
.rounded-input :deep(.ant-input-affix-wrapper) {
    border-radius: 8px;
}
</style>
